name: Publish to Pub.dev

on:
  pull_request:
    branches: [ master ]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: Publish Dart/Flutter package
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.DART_PUB_CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true

